version: '3'  # Docker Compose version

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root
    privileged: true
    environment:
      DOCKER_HOST: "tcp://dind:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs-client:/certs/client:ro
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - project2-compose_jenkins  # Ensure Jenkins is on the same network

  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      - project2-compose_jenkins  # Connect DinD to the same network

volumes:
  jenkins-data:
  docker-certs-ca:
  docker-certs-client:

networks:
  project2-compose_jenkins:  # Define the custom network
